### ISSUE TITLE
Add waterways overlay to map

### ISSUE THREAD

**Issue by kmal808** [CodeWithAloha/Hawaii-Zoning-Atlas#13]
### Overview
Add waterways overlay to map 

### Action Items
Find and add waterways data to hydro.min.geojson

### Resources/Instructions
Waterways tooltip has some info on where their data is from. 

```<label class="f5" title="Includes ponds, lakes, oceans, swamps, glaciers, and the area covered by large rivers, streams, and/or canals. Data from TIGER/Line Shapefile, 2010, CT, Current Area Hydrography Shapefile.">```

#### Potentially relevant resources
https://catalog.data.gov/dataset/tiger-line-shapefile-current-state-hawaii-census-tracts
https://www.usgs.gov/national-hydrography/access-national-hydrography-products

**Comment by ggordn3r** [comment]
See Areal Hydrography in this geodatabase from Census TIGER/Line 2022. Should contain the data we're looking for.
[tlgdb_2022_a_15_hi.gdb.zip](https://github.com/CodeforHawaii/Hawaii-Zoning-Atlas/files/9894671/tlgdb_2022_a_15_hi.gdb.zip)
