### ISSUE TITLE
[TASK] Create a GitHub Action that pulls data from the Hawaii Zoning Atlas Master spreadsheet

### ISSUE THREAD

**Issue by tyliec** [CodeWithAloha/Hawaii-Zoning-Atlas#19]
# Overview

```mermaid
sequenceDiagram
    participant Actions
    participant Spreadsheet

    Actions->>Spreadsheet: Pull data for all the counties (Maui, Oahu, Big Island, Kauai)

    loop Validation
        Actions->>Actions: Validate the pulled data against a schema (prevent mistypings, blank lines, ...etc)
    end

    loop Commit
        Actions->>Actions: Commit the validated and changed files to this repository
    end
```

## Subtasks
- [x] #26
- [x] #27
-   - Validation could also be performed in the spreadsheet
- [x] #28

# Ideas
For Validation: https://json-schema.org/implementations.html#validators

**Comment by kmal808** [comment]
Is the action being a GH Action a requirement? I have the sheets merged and can bloop them into a repo folder, but not done as a GH Action.  
(Tried a GH Action first and I could grab the data but got stuck as a duck trying merging it so moved on to something that I could get to work 🤷)
See [combined sheets](https://github.com/kmal808/hi-data/blob/c904882e7fede9e36aa423b8dc2066e1ed2184a2/hawaii-data.csv)
_Note: this is attempting to match formatting of the final.csv stripping out the first row_

**Comment by tyliec** [comment]
> Is the action being a GH Action a requirement? I have the sheets merged and can bloop them into a repo folder, but not done as a GH Action. (Tried a GH Action first and I could grab the data but got stuck as a duck trying merging it so moved on to something that I could get to work 🤷) See [combined sheets](https://github.com/kmal808/hi-data/blob/c904882e7fede9e36aa423b8dc2066e1ed2184a2/hawaii-data.csv) _Note: this is attempting to match formatting of the final.csv stripping out the first row_

What do you have that is currently pulling the data and merging it - a script of some sort? I suggested to use GH Actions here to automate that process, we can shell out to the script you have in the Actions to run certain processes

**Comment by tyliec** [comment]
Closing since stale
