### ISSUE TITLE
Split Federal/State Overlay

### ISSUE THREAD

**Issue by ggordn3r** [CodeWithAloha/Hawaii-Zoning-Atlas#2]
Current implementation treats public land as a single on/off switch: Federal/State. A better implementation would separate federal and state into two overlay layers, (a) Federal and (b) State.

See `var loadFederalState = function()` in map.js.

Underlying data is saved to HZA Data repo.

**Comment by tyliec** [comment]
Closing in favor of https://github.com/CodeforHawaii/Hawaii-Zoning-Atlas/issues/25
