### ISSUE TITLE
2 minor text edits

### ISSUE THREAD

**Issue by ggordn3r** [CodeWithAloha/Hawaii-Zoning-Atlas#22]
### Overview
Text edits needed in 2 places:

### Action items
1. In pop-up guide, screen 1, replace this:

> Nonresidential: Districts where housing is not allowed to be an independent use. However, some nonresidential districts allow accessory dwelling units, like an apartment for a night watchman in a factory setting.

with this:

> Nonresidential: Districts where housing is not allowed to be an independent use. However, some nonresidential districts allow caretaker units, like an apartment for a night watchman in a factory setting.

2. In the settings panel, replace this:

> This interactive map shows how outdated zoning laws make it hard to build diverse, affordable housing.

with this:

> This interactive map explores how restrictive zoning laws can make it difficult to build diverse, affordable housing.

**Comment by ayushsingh01042003** [comment]
Hey this is my first time trying to contribute , 
Out of the two edits to be made i found the second one in the index.html file but was unable to find the first text to edit,
can you help me with where to find it
