### ISSUE TITLE
[EPIC] Hawaii Zoning Atlas Overlays

### ISSUE THREAD

**Issue by tyliec** [CodeWithAloha/Hawaii-Zoning-Atlas#25]
In the current implementation of our map, we have overlays as a portrayal for alternative/accessory datasets. This epic tracks improvements to these overlays, whether it be the addition of new overlays or edits to existing ones.

Current Overlays:
- Federal/State Public Lands
- Rail Transit Stations

Desired Overlays:
- [ ] [Sewage](https://github.com/CodeforHawaii/Hawaii-Zoning-Atlas/issues/17)
- [x] #37
- [x] #39
- [x] #38
- [x] #40

Potential Overlays:
- [ ] Elevation
- [x] #54

**Comment by tyliec** [comment]
Kauai overlay PR: https://github.com/CodeforHawaii/Hawaii-Zoning-Atlas/pull/34

**Comment by kmal808** [comment]
Can we close #38 #39 and checkoff #37 & [Hawaiian Homelands](https://github.com/CodeforHawaii/Hawaii-Zoning-Atlas/pull/46)??
All pau 🫡
