### ISSUE TITLE
Subtask: Create an action that runs a generic Jupyter notebook and exports a resulting file

### ISSUE THREAD

**Issue by tyliec** [CodeWithAloha/Hawaii-Zoning-Atlas#29]

**Comment by avenmia** [comment]
@tyliec  Does this only run the downloaded csvs through Jupyter Notebook? What about things like committing the result to the repository or is that separate issue?

**Comment by tyliec** [comment]
> 

Seperate issue, see https://github.com/CodeforHawaii/Hawaii-Zoning-Atlas/issues/31

**Comment by tyliec** [comment]
> @tyliec Does this only run the downloaded csvs through Jupyter Notebook? What about things like committing the result to the repository or is that separate issue?

Separate issue, see https://github.com/CodeforHawaii/Hawaii-Zoning-Atlas/issues/31
cc @avenmia
