### ISSUE TITLE
Federal Land Overlay

### ISSUE THREAD

**Issue by tyliec** [CodeWithAloha/Hawaii-Zoning-Atlas#39]

**Comment by ggordn3r** [comment]
Current implementation treats public land as a single on/off switch: Federal/State. A better implementation would separate federal and state into two overlay layers, (a) Federal and (b) State.

See var loadFederalState = function() in map.js.

Underlying data is saved to HZA Data repo. 

@kmal808 While working with this data, could you also try to reduce the size by running it through mapshaper with a 1 meter filter? It's currently 32MB.

**Comment by ggordn3r** [comment]
https://geoportal.hawaii.gov/datasets/HiStateGIS::government-land-ownership/about

**Comment by kmal808** [comment]
@ggordn3r PR #47 implements the separate overlays and minimizes the file sizes ✅ . 

In working with the gov-owned-land data, it appears that our og fed-state-dissolve file included DHHL and County owned lands in the fed-state overlay. DHHL is already handled, but would you like to see the County owned land as a.) its own overlay, b.) added back into either fed or state, or c.) left the way it currently is in PR #47 (not included)?
