### ISSUE TITLE
My First Issue

### ISSUE THREAD

**Issue by kcoronel** [CodeWithAloha/Hawaii-Zoning-Atlas#53]
The Grinch 

### The Grinch

**Comment by kcoronel** [comment]
hello I need help with x 

what's the status @kcoronel

**Comment by kmal808** [comment]
> hello I need help with x 
> 
> 
> 
> what's the status @kcoronel 

## I can help with x 

I will knock these out ⬇️ 
- [x] Add logo to navbar 🗺️
- [x] Test mobile layout 📱
- [x] Take over the world 🌎 


@jonathanswilcox do you have anything to add to this list? 

*@jonathanswilcox additions:
- [ ] Assess realistic timeline for remaining interviews & distribute duties 📆
- [ ] Install a coffee maker in the breakroom ☕️
- [ ] Determine times and location for company beach meet up 🌊

@kmal808 @kcoronel Who do I need to run these last two through? 😉

**Comment by kcoronel** [comment]
hey! this was a test issue, can we create a new one with the info above @kmal808 - thank you!

**Comment by kmal808** [comment]
Lol I know I was playing along 🤣 
The task list was a phony 🤥❌

**Comment by kcoronel** [comment]
@kmal808 LMFAOO! love it! thank you

**Comment by jonathanswilcox** [comment]
ps- Wish I could have been there for the meeting yesterday! Were you able to onboard everyone here to Github? I'll check the meeting notes to see what I need to catch up on!

Also- why's the UI/UX label a lipstick container? 🙈

**Comment by kmal808** [comment]
> *@jonathanswilcox additions:
> 
> * [ ]  Assess realistic timeline for remaining interviews & distribute duties 📆
> * [ ]  Install a coffee maker in the breakroom ☕️
> * [ ]  Determine times and location for company beach meet up 🌊
> 
> @kmal808 @kcoronel Who do I need to run these last two through? 😉

As someone with no authority to do so, I approve all of these additions giving extra priority to the last two ✅ 🤣
