### ISSUE TITLE
🐛 [BUG] - Intro Driver Overlay

### ISSUE THREAD

**Issue by kmal808** [CodeWithAloha/Hawaii-Zoning-Atlas#69]
### Contact Details

kmal@moar.maps.com

### What happened?

When navigating through the Introductory Driver tour, after clicking the `next` button on the  `Select Permitted Residential Uses` popup. the darkening overlay goes away and then returns after clicking `next` on the `Click the map to learn about your county ` popup.

### Reproduction steps

```bash
1. Go to 'https://hawaiizoningatlas.com'
2. Click on 'Next' to begin the tour
3. After two tour popups the screen gets blindingly light
4. Click 'Next' again and the dark overlay is back
```

### Screenshots

https://user-images.githubusercontent.com/20919083/219350798-1b0f93e5-c9ea-47e9-9452-5e0f2db4bd23.mp4

### Browsers

Safari, Microsoft Edge

### OS

Linux, Mac

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tyliec** [comment]
:fishsticks:

**Comment by kmal808** [comment]
Closing per fish sticks ⬆️ (_aka chopped wood_ 🪵)
