### ISSUE TITLE
Subtask:  📃 Setting base typeface

### ISSUE THREAD

**Issue by kmal808** [CodeWithAloha/Hawaii-Zoning-Atlas#73]
# Overview
The research and testing done during the Legend 1 Design System has informed that the following would be ideal typefaces and font options

<img width="625" alt="Screenshot 2023-02-21 at 9 20 50 PM" src="https://user-images.githubusercontent.com/20919083/220838780-012ea3a8-c69e-4bd6-aaf1-a69eef623b4c.png">

# Action Items
Replace the current heading 2 and body `font-size`, `font-family`, `letter-spacing`, and `font-weight` with the options shown in the above image and in the UX Teams Figma file.

# Resources
[Figma](https://www.figma.com/file/T8pIgx0d4iOwb2CkxUoKn6/Web-Application?node-id=0%3A1&t=rSSgHneMJt7AYL5x-0)
[Fontshare Zodiac](https://www.fontshare.com/fonts/zodiak)
[Fontshare Red Hat Display](https://www.fontshare.com/fonts/red-hat-display)

### Additional Info Requested
~~Should the `font-family: Red Hat Display` be used on all headings or just H2's? Excuse my ignorance if this is obvious~~

**Comment by kenz-bee** [comment]
@kmal808  At the moment, Red Hat should be used for all headings. This H2 is all that is presented on the current legend
