### ISSUE TITLE
🐛 [BUG] - Zone Opacity control not working

### ISSUE THREAD

**Issue by franciscocha** [CodeWithAloha/Hawaii-Zoning-Atlas#99]
### Contact Details

franciscocha@gmail.com

### What happened?

Zone Opacity control bar doesn't seem to actually change the opacity

### Reproduction steps

```bash
1. Go to https://hawaiizoningatlas.com
2. Adjusting the Zone Opacity control bar doesn't actually change the opacity
```

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franciscocha** [comment]
**Screen Shots**
![100 Opacity](https://github.com/CodeWithAloha/Hawaii-Zoning-Atlas/assets/23488684/7340c4a8-8951-402c-a008-a3a02531d818)
![0 Opacity](https://github.com/CodeWithAloha/Hawaii-Zoning-Atlas/assets/23488684/98e50c1a-eb4b-42d9-95ac-10b1884b87b5)

**Comment by tyliec** [comment]
Solved in https://github.com/CodeWithAloha/Hawaii-Zoning-Atlas/pull/101
